In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import json
import re

# Load the Excel file and the specific sheet
file_path = 'D:/Project 3 Cardheko/delhi_cars.xlsx'
df = pd.read_excel(file_path)

# Function to convert Python-style dictionary strings to valid JSON
def convert_to_json_format(text):
    text = text.replace("'", '"').replace("None", "null").replace("True", "true").replace("False", "false")
    text = re.sub(r'(?<!")(\b\w+\b)(?=:)', r'"\1"', text)
    return text

# Apply the conversion to the 'new_car_detail' column
df['new_car_detail'] = df['new_car_detail'].apply(convert_to_json_format)

# Function to flatten the JSON data
def flatten_json_column(df, column_name):
    return pd.json_normalize(df[column_name].apply(json.loads))

# Flatten the 'new_car_detail' column
flattened_details = flatten_json_column(df, 'new_car_detail')

# Display the structured data
flattened_details.head()

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,7121,GTX Plus Diesel AT,₹ 19 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,1449,1.6 VTVT S,₹ 7.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,6837,200,₹ 56 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,10403,VXI,₹ 5.23 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,5362,1.6 VTVT E Plus,₹ 7.65 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [3]:
#Optionally, save the structured data to a new CSV file
flattened_details.to_csv('structured_new_car_details2.csv', index=False)

In [4]:
import pandas as pd
import json
import re

# Load the Excel file and the specific sheet
file_path = 'D:/Project 3 Cardheko/delhi_cars.xlsx'
df = pd.read_excel(file_path)
df['new_car_overview'] = df['new_car_overview'].apply(lambda x:json.loads(x.replace("'",'"').replace('None',"1")))
def car_overview_dict_creator(overview):
    all_overviews = {}
    for dictionary in overview['top']:
        all_overviews.update({dictionary.get('key'):dictionary.get('value')})
    return all_overviews

df.new_car_overview = df.new_car_overview.apply(lambda overview: car_overview_dict_creator(overview))

overview_df = pd.DataFrame(df.new_car_overview.to_list())
overview_df

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,Ownership,Engine Displacement,Transmission,Year of Manufacture,RTO
0,2022,Third Party insurance,Diesel,5 Seats,"10,000 Kms",First Owner,1493 cc,Automatic,2022,NaN
1,May 2016,Zero Dep,Petrol,5 Seats,"57,437 Kms",Second Owner,1591 cc,Manual,2016,HR51
2,Dec 2020,Comprehensive,Petrol,5 Seats,"8,000 Kms",First Owner,1991 cc,Automatic,2020,DL01
3,Jan 2019,Comprehensive,Petrol,5 Seats,"28,151 Kms",Second Owner,1197 cc,Manual,2018,DL4C
4,2017,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2017,DL8C
...,...,...,...,...,...,...,...,...,...,...
1480,2019,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1497 cc,Automatic,2019,DL4C
1481,2021,Third Party insurance,Petrol,5 Seats,"20,000 Kms",First Owner,1197 cc,Manual,2021,NaN
1482,2011,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2011,NaN
1483,Oct 2019,Third Party insurance,Diesel,5 Seats,"38,000 Kms",First Owner,1582 cc,Manual,2019,HR26
1484,NaN,Third Party insurance,Diesel,6 Seats,"7,000 Kms",NaN,1996 cc,Automatic,2023,NaN

In [5]:
overview_df.to_csv('structured_new_car_overview2.csv', index=False)

In [6]:
import pandas as pd
import json

# Load the Excel file
file_path = 'D:/Project 3 Cardheko/delhi_cars.xlsx'
df = pd.read_excel(file_path)

# Clean and parse JSON-like strings in 'new_car_feature'
df['new_car_feature'] = df['new_car_feature'].apply(lambda x: json.loads(x.replace("'", '"').replace('None', '1')))

# Function to flatten the 'new_car_feature' column
def flatten_car_feature(feature):
    # Extract 'commonIcon'
    common_icon = feature.get('commonIcon', None)
    
    # Extract 'top' features
    top_features = {f"Top Feature {i+1}": item['value'] for i, item in enumerate(feature.get('top', []))}
    
    # Extract 'data' features with headings and subheadings
    data_features = {}
    for group in feature.get('data', []):
        heading = group['heading']
        sub_heading = group['subHeading']
        for i, item in enumerate(group.get('list', [])):
            key = f"{heading}_{sub_heading}_Feature {i+1}"
            data_features[key] = item['value']
    
    return {**top_features, **data_features, 'commonIcon': common_icon}

# Apply the function to extract and flatten data from 'new_car_feature'
df['flattened_features'] = df['new_car_feature'].apply(flatten_car_feature)

# Convert the flattened features into a DataFrame
features_df = pd.DataFrame(df['flattened_features'].tolist())

# Concatenate the original DataFrame with the new features DataFrame
result_df = pd.concat([df.drop(columns=['new_car_feature', 'flattened_features']), features_df], axis=1)

# Display the resulting DataFrame
print("Final DataFrame with all features in columns, including commonIcon:")
result_df.head()

Final DataFrame with all features in columns, including commonIcon:

,new_car_detail,new_car_overview,new_car_specs,car_links,Top Feature 1,Top Feature 2,Top Feature 3,Top Feature 4,Top Feature 5,Top Feature 6,...,Comfort & Convenience_Comfort_Feature 37,Safety_Safety_Feature 45,Safety_Safety_Feature 46,Safety_Safety_Feature 47,Safety_Safety_Feature 48,Entertainment & Communication_Entertainment_Feature 17,Entertainment & Communication_Entertainment_Feature 18,Entertainment & Communication_Entertainment_Feature 19,Entertainment & Communication_Entertainment_Feature 20,Entertainment & Communication_Entertainment_Feature 21
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Optionally, save the structured data to a new CSV file
result_df.to_csv('structured_new_car_feature2.csv', index=False)

In [8]:
import pandas as pd
import json

# Load the Excel file
file_path = 'D:/Project 3 Cardheko/delhi_cars.xlsx'
df = pd.read_excel(file_path)

# Clean and parse JSON-like strings in 'new_car_specs'
df['new_car_specs'] = df['new_car_specs'].apply(lambda x: json.loads(x.replace("'", '"').replace('None', '1')))

# Function to flatten the 'new_car_specs' column
def flatten_car_specs(specs):
    # Initialize a dictionary to store the flattened data
    flattened_data = {}
    
    
    
    # Extract 'top' specifications
    for item in specs.get('top', []):
        key = item.get('key')
        value = item.get('value')
        if key:  # Ensure key is not None
            flattened_data[key] = value
    
    # Extract 'data' features with headings and subheadings
    for group in specs.get('data', []):
        for item in group.get('list', []):
            key = item.get('key')
            value = item.get('value')
            if key:  # Ensure key is not None
                flattened_data[key] = value
    
    return flattened_data

# Apply the function to extract and flatten data from 'new_car_specs'
df['flattened_specs'] = df['new_car_specs'].apply(flatten_car_specs)

# Convert the flattened specs into a DataFrame
specs_df = pd.DataFrame(df['flattened_specs'].tolist())

# Concatenate the original DataFrame with the new specs DataFrame
result_df = pd.concat([df.drop(columns=['new_car_specs', 'flattened_specs']), specs_df], axis=1)

# Display the resulting DataFrame
print("Final DataFrame with keys as column names and values as rows:")
result_df.head()

Final DataFrame with keys as column names and values as rows:

,new_car_detail,new_car_overview,new_car_feature,car_links,Mileage,Engine,Max Power,Torque,Wheel Size,Seats,...,Super Charger,Turning Radius,Top Speed,Acceleration,Gross Weight,Front Tread,Rear Tread,BoreX Stroke,Compression Ratio,Ground Clearance Unladen
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/used-car-details/used...,18 kmpl,1493 CC,113.43bhp@4000rpm,250Nm,17,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/buy-used-car-details/...,15.29 kmpl,1591 CC,121.3bhp@6400rpm,151Nm,NaN,5,...,No,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/used-car-details/used...,12.74 kmpl,1991 CC,197bhp@5500-6100rpm,320nm,19,5,...,NaN,NaN,217 Kmph,NaN,2360kg,NaN,NaN,NaN,NaN,NaN
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/buy-used-car-details/...,22.38 kmpl,1197 CC,88.50bhp@6000rpm,113Nm,NaN,5,...,NaN,4.8,NaN,NaN,1335,1530,1530,NaN,NaN,NaN
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/used-car-details/used...,15.29 kmpl,1591 CC,121.3bhp@6400rpm,151Nm,NaN,5,...,No,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Optionally, save the structured data to a new CSV file
result_df.to_csv('structured_new_car_specs2.csv', index=False)

In [10]:

df1 = pd.read_csv('D:/Project 3 Cardheko/structured_new_car_details2.csv')
df2 = pd.read_csv('D:/Project 3 Cardheko/structured_new_car_feature2.csv')
df3 = pd.read_csv('D:/Project 3 Cardheko/structured_new_car_overview2.csv')
df4 = pd.read_csv('D:/Project 3 Cardheko/structured_new_car_specs2.csv')

# Concatenate DataFrames horizontally
final_concat_df = pd.concat([df1, df2, df3, df4], axis=1)

# Display the final concatenated DataFrame
final_concat_df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Super Charger,Turning Radius,Top Speed,Acceleration,Gross Weight,Front Tread,Rear Tread,BoreX Stroke,Compression Ratio,Ground Clearance Unladen
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,...,No,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,...,NaN,NaN,217 Kmph,NaN,2360kg,NaN,NaN,NaN,NaN,NaN
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,...,NaN,4.8,NaN,NaN,1335,1530,1530,NaN,NaN,NaN
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,...,No,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,...,No,5.3 metres,195 Kmph,10 Seconds,1455kg,1490mm,1480mm,73.0 X 89.4 mm,10.3:1,NaN
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,...,No,5.2 metres,196km/hr,10.5 Seconds,NaN,NaN,NaN,77.0mm X 85.44mm,10.5;1,NaN
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,...,No,5.3 metres,160.58kmph,10.83 s,NaN,NaN,NaN,NaN,NaN,190mm
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
final_concat_df['city'] = 'Delhi'

In [12]:
final_concat_df.head()

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Top Speed,Acceleration,Gross Weight,Front Tread,Rear Tread,BoreX Stroke,Compression Ratio,Ground Clearance Unladen,city
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delhi
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,...,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,Delhi
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,...,NaN,217 Kmph,NaN,2360kg,NaN,NaN,NaN,NaN,NaN,Delhi
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,...,4.8,NaN,NaN,1335,1530,1530,NaN,NaN,NaN,Delhi
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,...,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,Delhi

In [13]:
final_concat_df.to_csv('Delhi.csv',index=False)