In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import json
import re

# Load the Excel file and the specific sheet
file_path = 'D:/Project 3 Cardheko/jaipur_cars.xlsx'
df = pd.read_excel(file_path)

# Function to convert Python-style dictionary strings to valid JSON
def convert_to_json_format(text):
    text = text.replace("'", '"').replace("None", "null").replace("True", "true").replace("False", "false")
    text = re.sub(r'(?<!")(\b\w+\b)(?=:)', r'"\1"', text)
    return text

# Apply the conversion to the 'new_car_detail' column
df['new_car_detail'] = df['new_car_detail'].apply(convert_to_json_format)

# Function to flatten the JSON data
def flatten_json_column(df, column_name):
    return pd.json_normalize(df[column_name].apply(json.loads))

# Flatten the 'new_car_detail' column
flattened_details = flatten_json_column(df, 'new_car_detail')

# Display the structured data
flattened_details.head()

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,1487,Asta 1.4 CRDi,₹ 5.10 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,10403,VXI,₹ 3.81 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,3982,VXI AT,₹ 3.20 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,5602,1.2 Kappa Magna BSIV,₹ 4.20 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,4319,AMT VXI,₹ 3.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [3]:
#Optionally, save the structured data to a new CSV file
flattened_details.to_csv('structured_new_car_details4.csv', index=False)

In [4]:
import pandas as pd
import json
import re

# Load the Excel file and the specific sheet
file_path = 'D:/Project 3 Cardheko/jaipur_cars.xlsx'
df = pd.read_excel(file_path)
df['new_car_overview'] = df['new_car_overview'].apply(lambda x:json.loads(x.replace("'",'"').replace('None',"1")))
def car_overview_dict_creator(overview):
    all_overviews = {}
    for dictionary in overview['top']:
        all_overviews.update({dictionary.get('key'):dictionary.get('value')})
    return all_overviews

df.new_car_overview = df.new_car_overview.apply(lambda overview: car_overview_dict_creator(overview))

overview_df = pd.DataFrame(df.new_car_overview.to_list())
overview_df

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2015,Third Party insurance,Diesel,5 Seats,"1,20,000 Kms",RJ13,Second Owner,1396 cc,Manual,2015.0
1,Jan 2012,Third Party,Petrol,5 Seats,"66,951 Kms",RJ14,First Owner,1197 cc,Manual,2012.0
2,2016,Third Party insurance,Petrol,5 Seats,"80,000 Kms",RJ14,Second Owner,998 cc,Automatic,2016.0
3,Apr 2017,Third Party insurance,Petrol,5 Seats,"44,392 Kms",RJ14,First Owner,1197 cc,Manual,2017.0
4,2016,Third Party insurance,Petrol,5 Seats,"40,000 Kms",RJ14,First Owner,998 cc,Automatic,2016.0
...,...,...,...,...,...,...,...,...,...,...
1115,2011,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",RJ14,First Owner,1199 cc,Manual,2011.0
1116,2007,Third Party insurance,Petrol,5 Seats,"70,000 Kms",RJ30,First Owner,796 cc,Manual,2007.0
1117,2022,Third Party insurance,Petrol,5 Seats,"20,000 Kms",RJ45,First Owner,999 cc,Manual,2022.0
1118,2009,Third Party insurance,Petrol,5 Seats,"40,000 Kms",NaN,First Owner,796 cc,Manual,2009.0
1119,2018,Third Party insurance,Petrol,5 Seats,"80,000 Kms",UP82,First Owner,1197 cc,Manual,2018.0

In [5]:
overview_df.to_csv('structured_new_car_overview4.csv', index=False)

In [6]:
import pandas as pd
import json

# Load the Excel file
file_path = 'D:/Project 3 Cardheko/jaipur_cars.xlsx'
df = pd.read_excel(file_path)

# Clean and parse JSON-like strings in 'new_car_feature'
df['new_car_feature'] = df['new_car_feature'].apply(lambda x: json.loads(x.replace("'", '"').replace('None', '1')))

# Function to flatten the 'new_car_feature' column
def flatten_car_feature(feature):
    # Extract 'commonIcon'
    common_icon = feature.get('commonIcon', None)
    
    # Extract 'top' features
    top_features = {f"Top Feature {i+1}": item['value'] for i, item in enumerate(feature.get('top', []))}
    
    # Extract 'data' features with headings and subheadings
    data_features = {}
    for group in feature.get('data', []):
        heading = group['heading']
        sub_heading = group['subHeading']
        for i, item in enumerate(group.get('list', [])):
            key = f"{heading}_{sub_heading}_Feature {i+1}"
            data_features[key] = item['value']
    
    return {**top_features, **data_features, 'commonIcon': common_icon}

# Apply the function to extract and flatten data from 'new_car_feature'
df['flattened_features'] = df['new_car_feature'].apply(flatten_car_feature)

# Convert the flattened features into a DataFrame
features_df = pd.DataFrame(df['flattened_features'].tolist())

# Concatenate the original DataFrame with the new features DataFrame
result_df = pd.concat([df.drop(columns=['new_car_feature', 'flattened_features']), features_df], axis=1)

# Display the resulting DataFrame
print("Final DataFrame with all features in columns, including commonIcon:")
result_df.head()

Final DataFrame with all features in columns, including commonIcon:

,new_car_detail,new_car_overview,new_car_specs,car_links,Top Feature 1,Top Feature 2,Top Feature 3,Top Feature 4,Top Feature 5,Top Feature 6,...,Exterior_Exterior_Feature 24,Exterior_Exterior_Feature 25,Safety_Safety_Feature 38,Safety_Safety_Feature 39,Safety_Safety_Feature 40,Safety_Safety_Feature 41,Safety_Safety_Feature 42,Entertainment & Communication_Entertainment_Feature 14,Exterior_Exterior_Feature 26,Entertainment & Communication_Entertainment_Feature 15
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Optionally, save the structured data to a new CSV file
result_df.to_csv('structured_new_car_feature4.csv', index=False)

In [8]:
import pandas as pd
import json

# Load the Excel file
file_path = 'D:/Project 3 Cardheko/jaipur_cars.xlsx'
df = pd.read_excel(file_path)

# Clean and parse JSON-like strings in 'new_car_specs'
df['new_car_specs'] = df['new_car_specs'].apply(lambda x: json.loads(x.replace("'", '"').replace('None', '1')))

# Function to flatten the 'new_car_specs' column
def flatten_car_specs(specs):
    # Initialize a dictionary to store the flattened data
    flattened_data = {}
    
    
    
    # Extract 'top' specifications
    for item in specs.get('top', []):
        key = item.get('key')
        value = item.get('value')
        if key:  # Ensure key is not None
            flattened_data[key] = value
    
    # Extract 'data' features with headings and subheadings
    for group in specs.get('data', []):
        for item in group.get('list', []):
            key = item.get('key')
            value = item.get('value')
            if key:  # Ensure key is not None
                flattened_data[key] = value
    
    return flattened_data

# Apply the function to extract and flatten data from 'new_car_specs'
df['flattened_specs'] = df['new_car_specs'].apply(flatten_car_specs)

# Convert the flattened specs into a DataFrame
specs_df = pd.DataFrame(df['flattened_specs'].tolist())

# Concatenate the original DataFrame with the new specs DataFrame
result_df = pd.concat([df.drop(columns=['new_car_specs', 'flattened_specs']), specs_df], axis=1)

# Display the resulting DataFrame
print("Final DataFrame with keys as column names and values as rows:")
result_df.head()

Final DataFrame with keys as column names and values as rows:

,new_car_detail,new_car_overview,new_car_feature,car_links,Mileage,Engine,Max Power,Torque,Wheel Size,Seats,...,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Gross Weight,BoreX Stroke,Compression Ratio,Ground Clearance Unladen
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/used-car-details/used...,22.54 kmpl,1396 CC,88.73bhp@4000rpm,219.7Nm,16,5,...,180 Kmph,11.9 Seconds,Tubeless,16,5,295-litres,NaN,NaN,NaN,NaN
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/buy-used-car-details/...,22.38 kmpl,1197 CC,88.50bhp@6000rpm,113Nm,NaN,5,...,NaN,NaN,"Radial, Tubeless",NaN,5,268,1335,NaN,NaN,NaN
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/used-car-details/used...,23.1 kmpl,998 CC,67.04bhp@6000rpm,90Nm,NaN,5,...,150 Kmph,15.05 Seconds,"Tubeless, Radial",NaN,5,235-litres,1250kg,73 X 82 mm,11.0:1,NaN
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/buy-used-car-details/...,18.9 kmpl,1197 CC,81.86bhp@6000rpm,113.75nm,NaN,5,...,165 Kmph,12.9 Seconds,Tubeless,NaN,5,256,NaN,NaN,NaN,NaN
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...",https://www.cardekho.com/used-car-details/used...,20.51 kmpl,998 CC,67bhp@6000rpm,90Nm,NaN,5,...,152 kmph,18.6 Seconds,Tubeless Tyres,NaN,5,180-liters,1350kg,69 x 72 mm,NaN,NaN

In [9]:
# Optionally, save the structured data to a new CSV file
result_df.to_csv('structured_new_car_specs4.csv', index=False)

In [10]:

df1 = pd.read_csv('D:/Project 3 Cardheko/structured_new_car_details4.csv')
df2 = pd.read_csv('D:/Project 3 Cardheko/structured_new_car_feature4.csv')
df3 = pd.read_csv('D:/Project 3 Cardheko/structured_new_car_overview4.csv')
df4 = pd.read_csv('D:/Project 3 Cardheko/structured_new_car_specs4.csv')

# Concatenate DataFrames horizontally
final_concat_df = pd.concat([df1, df2, df3, df4], axis=1)

# Display the final concatenated DataFrame
final_concat_df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Gross Weight,BoreX Stroke,Compression Ratio,Ground Clearance Unladen
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,180 Kmph,11.9 Seconds,Tubeless,16,5.0,295-litres,NaN,NaN,NaN,NaN
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,NaN,NaN,"Radial, Tubeless",NaN,5.0,268,1335,NaN,NaN,NaN
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,150 Kmph,15.05 Seconds,"Tubeless, Radial",NaN,5.0,235-litres,1250kg,73 X 82 mm,11.0:1,NaN
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,165 Kmph,12.9 Seconds,Tubeless,NaN,5.0,256,NaN,NaN,NaN,NaN
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,152 kmph,18.6 Seconds,Tubeless Tyres,NaN,5.0,180-liters,1350kg,69 x 72 mm,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,NaN,NaN,"Tubeless,Radial",14,5.0,170-litres,NaN,NaN,NaN,NaN
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,137km/hr,17.7 seconds,"Tubeless,Radial",12,5.0,NaN,1140kg,68.5 x 72.0 mm,NaN,NaN
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,NaN,NaN,"Tubeless, Radial",16,5.0,405,NaN,NaN,NaN,NaN
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,137km/hr,17.7 seconds,"Tubeless,Radial",12,5.0,NaN,1140kg,68.5 x 72.0 mm,NaN,NaN
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,180 Kmph,12.36 seconds,"Tubeless,Radial",NaN,5.0,339-litres,1340kg,NaN,NaN,NaN

In [11]:
final_concat_df['city'] = 'Jaipur'

In [12]:
final_concat_df.head()

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Gross Weight,BoreX Stroke,Compression Ratio,Ground Clearance Unladen,city
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,11.9 Seconds,Tubeless,16,5.0,295-litres,NaN,NaN,NaN,NaN,Jaipur
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,NaN,"Radial, Tubeless",NaN,5.0,268,1335,NaN,NaN,NaN,Jaipur
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,15.05 Seconds,"Tubeless, Radial",NaN,5.0,235-litres,1250kg,73 X 82 mm,11.0:1,NaN,Jaipur
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,12.9 Seconds,Tubeless,NaN,5.0,256,NaN,NaN,NaN,NaN,Jaipur
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,18.6 Seconds,Tubeless Tyres,NaN,5.0,180-liters,1350kg,69 x 72 mm,NaN,NaN,Jaipur

In [13]:
final_concat_df.to_csv('Jaipur.csv',index=False)